### ISSUE TITLE
Save Settings to NSUserDefaults

### ISSUE THREAD

**Issue by ndonald2** [Raizlabs/RZDebugMenu#12]
Thinking about how we want to persist settings, NSUserDefaults is probably a good choice. It's an OS-level feature so we aren't doing something proprietary to this component, which means we don't need to go through the overhead of debugging our own disk persistence.

The default settings values from the plist should be registered as defaults in `NSUserDefaults` when the debug menu is initialized (using `registerDefaults`). We may want to consider always prepending "DEBUG" to each key so that there is less risk of trampling existing keys in the user defaults.

Every time the debug menu is dismissed, we need to enumerate all the settings, see which have changed, and write the new values to user defaults. It would also be convenient to have a class method on `RZDebugMenu` that allows retrieval of a value for a provided settings key:

`+ (id)debugSettingForKey:(NSString *)key;`

Eventually it will be good to also have some form of a notification system that sends out a notification (or maybe executes a registered block) when a particular setting changes, so a developer can have components in their app observe changes to settings and respond accordingly. But let's not worry about that now, that can be the next task.
### Tasks
- [x] Upon init, register the default settings in `NSUserDefaults`
- [x] When dismissing the debug menu, find changed settings and write the new values to user defaults
- [x] Implement a method on `RZDebugMenu` to retrieve a settings value for a particular key from the current settings in user defaults.
