### ISSUE TITLE
Class interface for enabling menu

### ISSUE THREAD

**Issue by ndonald2** [Raizlabs/RZDebugMenu#6]
Create a new class `RZDebugMenu` with only class methods. Internally, this class can have shared state or a private shared instance to manage the plist settings interface and a separate window object for the menu to be displayed in.

Enabling the debug menu will be as simple as:

``` objective-c
#if (DEBUG)
[RZDebugMenu enable];
#end
```

which will enable the separate window and add a global gesture to the main window, so the menu can be triggered from anywhere in the app.

This will be sort of tricky - separate `UIWindow` instances and global gestures can be difficult to do correctly. I am happy to answer any questions.
### Tasks
- [x] `RZDebugMenu` class interface
  - Right now just an `enable` method
  - Can have a private internal shared instance, but alloc/init on class directly should throw exception.
- [x] Calling `enable` does the following:
  - [x] Create separate `UIWindow` with a clear, passthrough root view controller
  - [x] Add a gesture to the main app's window to present the debug menu
  - [x] Debug menu is presented from the separate `UIWindow`'s root VC
### Info
- The window will need to be a subclass of `UIWindow` that overrides `hitTest:` to return nil for any touches that occur in the clear root view controller. This will allow touches to pass through to the main app
- The private shared instance should retain the window, gesture, and root view controller, and can act as the gesture's target. The selector should modally present the debug menu from the root view controller
